# Generated by Django 3.2.22 on 2023-11-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(default='')),
                ('email', models.EmailField(max_length=254)),
                ('profissao', models.CharField(max_length=100)),
            ],
        ),
    ]
